server:
  port: 8082

spring:
  application:
    name: file-server
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://81.68.212.127:3306/Accounter
    username: root
    password: onelastkiss
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 5000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
file:
  path:
    win: E:\MyProject\Accounter-file\
    mac: /Library/MyProjects/Accounter-file/
    linux: /tmp/file/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka