server:
  port: 80

spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://81.68.212.127:3306/Accounter
    username: root
    password: onelastkiss
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  data:
    redis:
      host: 81.68.212.127
      password: beautifulworld
      port: 6379
      timeout: 20000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000
  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则
      routes: #集合。
      # id: 唯一标识。默认是一个UUID
      # uri: 转发路径
      # predicates: 条件,用于请求网关路径的匹配规则
      # filters：配置局部过滤器的

      - id: AUTH-SERVER
        uri: lb://AUTH-SERVER
        predicates:
          - Path=/auth/**
        filters:

      - id: API-SERVER
        uri: lb://API-SERVER
        predicates:
          - Path=/api/**

      - id: FILE-SERVER
        uri: lb://FILE-SERVER
        predicates:
          - Path=/file/** , /images/**

      discovery:
        locator:
          enabled: true # 设置为true 请求路径前可以添加微服务名称
          lower-case-service-id: true # 允许为小写
  rabbitmq:
    host: 81.68.212.127
    port: 5672
    username: guest
    password: guest
    virtualHost: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka