textin:
  APPID: b494fe57a1b20d4c691ad80556069cfb
  SECRETCODE: 319b4ed6e88b83bf188d64a9ca130f0e


server:
  port: 8081
spring:
  application:
    name: textin-server
  datasource:
    url: jdbc:mysql://81.68.212.127:3306/Accounter
    username: root
    password: onelastkiss
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 5000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

file:
  path:
    win: E:\MyProject\Accounter-file\
    mac: /Library/MyProjects/Accounter-file/
    linux: /tmp/file/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka