mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: host.luke.common.pojo
server:
  port: 8080
spring:
  application:
    name: api-server
  datasource:
    url: jdbc:mysql://81.68.212.127:3306/Accounter
    username: root
    password: onelastkiss
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 5000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  data:
    mongodb:
      uri: mongodb://admin:samuraichamploo@81.68.212.127:27017/Accounter?authSource=admin&authMechanism=SCRAM-SHA-1
    redis:
      host: 81.68.212.127
      password: beautifulworld
      port: 6379
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000
  rabbitmq:
    host: 81.68.212.127
    port: 5672
    username: guest
    password: guest
    virtualHost: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

textin:
  APPID: b494fe57a1b20d4c691ad80556069cfb
  SECRETCODE: 319b4ed6e88b83bf188d64a9ca130f0e

file:
  path:
    win: E:\MyProject\Accounter-file\
    mac: /Library/MyProjects/Accounter-file/
    linux: /tmp/file/
